all:
  hosts:
    node1:
      ansible_host: 10.200.10.2
      ip: 10.200.10.2
      access_ip: 10.200.10.2
    node2:
      ansible_host: 10.200.10.3
      ip: 10.200.10.3
      access_ip: 10.200.10.3
    node3:
      ansible_host: 10.200.10.4
      ip: 10.200.10.4
      access_ip: 10.200.10.4
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
