all:
  hosts:
    node1:
      ansible_host: 10.200.10.21
      ip: 10.200.10.21
      access_ip: 10.200.10.21
    node2:
      ansible_host: 10.200.10.22
      ip: 10.200.10.22
      access_ip: 10.200.10.22
    node3:
      ansible_host: 10.200.10.23
      ip: 10.200.10.23
      access_ip: 10.200.10.23
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
