all:
  hosts:
    node1:
      ansible_host: 10.200.10.6
      ip: 10.200.10.6
      access_ip: 10.200.10.6
    node2:
      ansible_host: 10.200.10.7
      ip: 10.200.10.7
      access_ip: 10.200.10.7
    node3:
      ansible_host: 10.200.10.8
      ip: 10.200.10.8
      access_ip: 10.200.10.8
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
